### PR TITLE
v 1.5.1 fix silent error on subsequent invocations

### PR DESCRIPTION
**Pull request by dandalf**
Fixes bug specified in issue #53.
Also adds missing semi-colons. Really tempted to fix the mixed tabs & spaces, but left as is for a cleaner pull request.
Updated version to 1.5.1, executed build, and added a CHANGELOG.md.

### CODE REVIEW

**Comment by zetxek** [comment]
This might explain some intermitent hickups we were seeing in the lambda, once it had been already deployed. Despite having a constant flow of data, the function would only work during some hours per day...

**Comment by zetxek** [comment]
Confirmed: after deploying the function with this PR changes applied, it's reliable again.
Thanks @dandalf!

**Comment by benoittgt** [comment]
Good news. Thanks for the PR.

**Comment by martinssipenko** [comment]
@IanMeyers when can we expect this to be merged and released? Version 1.5.0 is broken.

**Comment by cnees** [comment]
Thanks for the fix, @dandalf! This is really handy, and came at just the time I needed it. 
I notice that d5977937938219dff02bf80d6aec40245fcf637f and 5dfb3422583fdaa1190b239400fd1b26296d9b84 have different content but the same commit message. It looks like one undoes some changes from the other. Do you think you could squash them or update the messages?

**Comment by dandalf** [comment]
@cnees sorry for the mess, I had committed some IDE files. Everything is now squashed into one commit. I have a dist file in there for v1.5.1, of course feel free to overwrite it or use your own versioning.

**Comment by adam-knights** [comment]
Can this be merged now? Useful fix..

**Comment by IanMeyers** [comment]
Thanks so much for the fix!

**Comment by ankon** [comment]
Could you please _tag_ the version 1.5.1 as well, so that it appears on the Releases page?

**Comment by IanMeyers** [comment]
Done

**Pull request merged**
